### ISSUE TITLE
RFE: Initial Maven build should be much faster

### ISSUE THREAD

**Issue by vorburger** [tqvarnst/quarkus-workshop#2]
@tqvarnst discussed that, especially during Workshops, it would be cool to have the initial `mvn quarkus:dev` be much faster than they currently are (for me, on a Minishift on Laptop, `07:27 min`).

This should be possible by caching / pre-loading `~/.m2`.  The https://github.com/redhat-developer/che-dockerfiles images do something like this which we may be able to leverage / build upon? I actually also did [something similar over here](https://github.com/quarkusio/quarkus/compare/master...vorburger:issue-1390_dev-container#diff-c4838d06cf92241aa52bc00c4678b7adR30) by using `dependency:go-offline dependency:resolve-plugins`.

**Comment by vorburger** [comment]
> The https://github.com/redhat-developer/che-dockerfiles images do something like this

and https://github.com/eclipse/che-dockerfiles has similar stuff - perhaps adding it there would be best?

@siamaksade FYI

**Comment by vorburger** [comment]
I spent some time rummaging around `eclipse/che-dockerfiles` VS `redhat-developer/che-dockerfiles` and I think I get it now... so _eclipse/che-dockerfiles_ has the "base" (e.g. non-OpenShift) containers (and those are available from https://registry.centos.org/che-stacks/centos-jdk8 etc.), whereas _redhat-developer/che-dockerfiles_ extends each of those by adding `oc` and Shift UID permissions stuff and what not (and those are available from https://quay.io/organization/openshiftio as `che-*`).

So I'll try to propose https://quarkus.io related PRs to those repos. (@cescoffier @benoitf @l0rd @dneary @dharmit @ibuziuk @kameshsampath @amisevsk @ibuziuk @dandreadis please shout if I misinterpreted anything.)

**Comment by l0rd** [comment]
`redhat-developer/che-dockerfiles` are used by che.openshift.io only.

**Comment by vorburger** [comment]
> `redhat-developer/che-dockerfiles` are used by che.openshift.io only.

My idea was that in addition to that, Workshops like this project could use that image as well, so instead of maintaining c2c5c3c  here in this project, this would then switch to use the proposed "upstream" Che Quarkus container, maintained together with the other respective Che containers after which it is very closely modeled. 

And http://che.openshift.io would also be a very cool place to show off Quarkus Che demos off on!

So https://github.com/redhat-developer/che-dockerfiles/pull/54 proposes to add what's required for this.

**Comment by amisevsk** [comment]
@vorburger You're also right about the maven dependencies; to avoid having to pull all dependencies when building some standard boosters, we have a step to just cache them in the image itself. This is, of course not ideal as it bloats the image size and has other issues that we'll need to address soon though (e.g. if .m2 is part of the image, then any *changes* to .m2 are lost when the container is stopped.
